on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Project
        run: mvn clean package

      - name: Generate Effective POM
        run: mvn help:effective-pom -Doutput=target/my-library.pom

      - name: List Target Directory
        run: ls -l target/

      - name: Setup Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}


      - name: Run JFrog CLI Ping and Publish Build Info
        run: |
          jf rt ping
          jf rt bce
          jf rt bag
          jf rt bp

      - name: Upload Artifact to Artifactory
        run: |
          jf rt u "target/my-library-*.pom" "libs-release-local/"